//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by ContourArx.rc
//
#define IDCALC                          3
#define IDC_BUTTON_PICK_PLINE           3
#define IDCROSS_SECTION                 4
#define IDC_BUTTON_PICK_VALIGNMENT      4
#define IDPROFILE                       5
#define IDD_ABOUTBOX                    100
#define IDR_TOOLBAR_CONTOUR             101
#define IDR_TOOLBAR_CONTOUR_NEW         102
#define IDD_DIALOG_CONTOUR_PARAM        103
#define IDS_STRING_AUTH_CODE_TAG        104
#define IDD_LICENSE_KEY_SELECTION       104
#define IDS_ABOUTBOX                    105
#define IDS_STRING_COMPANY              106
#define IDD_ABOUTME                     107
#define IDS_STRING_SW_NAME              108
#define IDD_GEN_POINTS                  109
#define IDS_STRING_AUTH_CODE_VAL        110
#define IDD_DIALOG_ANNOTATE_CONTOUR_PARAM 111
#define IDS_STRING_ACTIVATION_CODE_VAL  112
#define IDD_ANN_ENTITY_PROP_DLG         113
#define IDS_STRING_ACTIVATION_CODE_TAG  114
#define IDS_STRING_VERSION              115
#define IDS_STRING_AUTH_CODE_TAG2       116
#define IDS_STRING_AUTH_CODE_VAL2       117
#define IDS_STRING_ACTIVATION_CODE_VAL2 118
#define IDS_STRING_ACTIVATION_CODE_TAG2 119
#define IDR_MYSELF                      120
#define IDS_STRING_THIS_ARX_REG_PATH    120
#define IDR_CONTOUR                     121
#define IDS_STRING_THIS_ARX_NAME        121
#define IDD_DIALOG_ACTIVATION           122
#define IDD_TRANSLATE_TO_GRID           123
#define IDD_DIALOG_RESULT               124
#define IDD_GEN_POINTS_MULTI_SEG        125
#define IDR_MENU_POPUP                  126
#define IDD_PROFILE_CHG_Z               128
#define IDD_DIALOG_RAILWAY_DESIGN_TEMPLATE 129
#define IDD_XSEC_DATA                   132
#define IDD_DIALOG_CONTOUR_BOUNDARY     133
#define IDD_DIALOG_HORZ_PI_DATA         134
#define IDD_COORD_ANN_ENT_PROP_DLG      135
#define IDD_MODIFY_SURV_TAGS_DLG        141
#define IDD_PROFILE_DESIGN_DATA         142
#define IDC_EDIT_MIN_Z                  1000
#define IDC_EDIT_MAX_Z                  1001
#define IDC_BUTTON_FIND_MIN_Z           1002
#define IDC_BUTTON_FIND_MAX_Z           1003
#define IDC_EDIT_DISP_INSTALL_INFO      1003
#define IDC_LIST_INTERVELS              1004
#define IDC_BUTTON_ME                   1005
#define IDC_RADIO_PARAM_INTERVEL        1006
#define IDC_RADIO_LYR_AUTO              1007
#define IDC_EDIT_INTERVEL               1008
#define IDC_EDIT_NO_OF_INTERVEL         1009
#define IDC_EDIT_LYR                    1010
#define IDC_EDIT_INTERVEL_TOADD         1011
#define IDC_EDIT_ROTN                   1012
#define IDC_EDIT_RESULT                 1013
#define IDC_BUTTON_ADD_INTERVEL         1014
#define IDC_EDIT_LAB_TXT_SIZE           1014
#define IDC_CHECK1                      1015
#define IDC_EDIT_NUM_TXT_SIZE           1015
#define IDC_EDIT4                       1016
#define IDC_EDIT_ROW_HT                 1016
#define IDC_BUTTON_BASE_COLOR           1017
#define IDC_EDIT_PFL_LABEL_TXT_SIZE     1017
#define IDC_EDIT_CS_LABEL_TXT           1017
#define IDC_EDIT6                       1018
#define IDC_EDIT_BASE_CLR               1019
#define IDC_EDIT1                       1020
#define IDC_EDIT_EXAG_HORZ              1020
#define IDC_CHECK_AUTO_TXT_ANN          1021
#define IDC_EDIT_START                  1021
#define IDC_EDIT_X_ROFF                 1021
#define IDC_EDIT2                       1022
#define IDC_EDIT_TXT_HT                 1023
#define IDC_EDIT_END                    1023
#define IDC_EDIT_EXAG_VERT              1023
#define IDC_EDIT_Y_ROFF                 1023
#define IDC_EDIT3                       1024
#define IDC_BUTTON_DEL_INTERVEL         1025
#define IDC_EDIT_DATUM                  1025
#define IDC_EDIT_POINT_LYR              1026
#define IDC_STATIC_DIST                 1027
#define IDC_EDIT_TRG_LYR                1028
#define IDC_RADIO_LYR_CUR               1029
#define IDC_EDIT_CONTOUR_LYR_PREFIX     1030
#define IDC_RADIO_ANG_CNT_LINES         1031
#define IDC_EDIT_TXT_SPA                1032
#define IDC_RADIO_ANG_PATH              1033
#define IDC_EDIT_START_CHG              1033
#define IDC_EDIT                        1034
#define IDC_EDIT_SECTION_INTERVAL       1034
#define IDC_EDIT_CS_INTERVAL            1034
#define IDC_RADIO_LYR_USER              1035
#define IDC_EDIT_ORD_INTERVAL           1035
#define IDC_EDIT_SECTION_INTERVAL_MINOR 1035
#define IDC_STATIC_ELEV                 1036
#define IDC_EDIT_SHEET_WIDTH            1036
#define IDC_EDIT_PROFILE_PATH_WIDTH     1036
#define IDC_RADIO_ANG_USER              1037
#define IDC_EDIT_MAX_OFFSET             1037
#define IDC_STATIC_MSG                  1038
#define IDC_EDIT_SHEET_HEIGHT           1038
#define IDC_CHECK_SP_LEVEL              1039
#define IDC_EDIT_CS_INTERVAL_MINOR      1039
#define IDC_EDIT_SP_LEVEL_BLK           1040
#define IDC_EDIT_NAMEPLATE_WIDTH        1040
#define IDC_SPIN1                       1041
#define IDC_EDIT_SP_LEV_TXT_HT          1042
#define IDC_SPIN2                       1042
#define IDC_CHECK_FORCE_ANN             1043
#define IDC_EDIT_NAMEPLATE_HEIGHT       1043
#define IDC_EDIT_SP_LEV_ROT_ANGLE       1044
#define IDC_CHECK                       1045
#define IDC_EDIT_LYR_SP_LEVEL           1046
#define IDC_COMBO_BLK_NAME              1047
#define IDC_EDIT_BLK_SCALE              1048
#define IDC_COMBO_SEGMENT               1049
#define IDC_EDIT_ELEV_DIFF              1050
#define IDC_EDIT_NO_OF_PTS              1051
#define IDC_BUTTON_SET_ALL              1052
#define IDC_CHECK_NE_TAG                1053
#define IDC_CHECK_AUTO_DATUM            1054
#define IDC_BUTTON_SEL_BOUNDARY         1056
#define IDC_CHECK_CONSIDER_ALL_PTS      1057
#define IDC_LIST_LEV_RANGE              1058
#define IDC_CHECK_DEFINE_BOUNDARY       1058
#define IDC_EDIT_HOLE_NAME              1059
#define IDC_EDIT_DATUM_START            1060
#define IDC_LIST_HOLES                  1060
#define IDC_EDIT_DATUM_MARGIN           1061
#define IDC_BUTTON_NEW_HOLE             1061
#define IDC_EDIT_DATUM_END              1062
#define IDC_BUTTON_DEL_HOLE             1062
#define IDC_RADIO_DEG_OF_CURVE          1062
#define IDC_BUTTON_DEL_ALL_HOLES        1063
#define IDC_RADIO_CURVE_LENGTH          1063
#define IDC_EDIT_DATUM_DENOMINATOR      1063
#define IDC_BUTTON_ADD_RANGE            1064
#define IDC_BUTTON_VIEW_BOUNDARY        1064
#define IDC_RADIO_XTERNAL_LENGTH        1064
#define IDC_BUTTON_FILE                 1064
#define IDC_BUTTON_VIEW_HOLE            1065
#define IDC_RADIO_TANGENT_LENGTH        1065
#define IDC_EDIT_MARGIN                 1065
#define IDC_RADIO_RADIUS                1066
#define IDC_EDIT_DATUM_ELEV             1067
#define IDC_EDIT_DEG_OF_CURVE           1067
#define IDC_EDIT_ELEV_TAG               1068
#define IDC_EDIT_CURVE_LEN              1068
#define IDC_BUTTON_SAVE                 1068
#define IDC_STATIC_DISP_INSTALL_INFO    1069
#define IDC_STATIC_LICENSE              1070
#define IDC_EDIT_NORTHING_TAG           1071
#define IDC_EDIT_XTERNAL_LEN            1071
#define IDC_STATIC_DEV                  1071
#define IDC_EDIT_TANGENT_LEN            1072
#define IDC_STATIC_CONTACT              1072
#define IDC_EDIT_LYR_TOP_SURFACE        1073
#define IDC_EDIT_RADIUS                 1073
#define IDC_EDIT_EASTING_TAG            1074
#define IDC_EDIT_DATUM_TAG              1075
#define IDC_EDIT_PROFILE_LABEL          1076
#define IDC_EDIT_CS_LABEL_TAG           1076
#define IDC_EDIT_LYR_ORDINATE           1077
#define IDC_COMBO_SHEET                 1078
#define IDC_EDIT_DISTANCE_TAG           1079
#define IDC_EDIT_OFFSET_TAG             1079
#define IDC_EDIT_LYR_ANNOTATION         1080
#define IDC_EDIT_LYR_AXIS               1081
#define IDC_EDIT_CUM_DISTANCE_TAG       1082
#define IDC_CHECK_DRAW_NE               1082
#define IDC_BUTTON_DEL_RANGE            1083
#define IDC_BUTTON_LICENSE_RESET        1083
#define IDC_CHECK_DRAW_SECTIONS_ON_POI  1084
#define IDC_RADIO_CUTTING               1084
#define IDC_RADIO_FILLING               1085
#define IDC_STATIC_DUMMY                1088
#define IDC_STATIC_DEFINE_DSGN_SECTION  1090
#define IDC_STATIC_SET_DSGN_SECTION     1091
#define IDC_STATIC_VALIGNMENT_DATA      1092
#define IDC_COMBO1                      1095
#define ID_BUTTON_GENTIN                40000
#define ID_DRAWCONTOUR                  40001
#define ID_CONTOUR_PARAM                40002
#define ID_BUTTON_IMPORTDATA            40003
#define ID_ABOUT                        40004
#define ID_BUTTON_GEN_POINTS            40005
#define ID_BUTTON_ADD_POINTS            40006
#define ID_BUTTON_HARD_BREAK            40007
#define ID_BUTTON_AUTO_ANN              40008
#define ID_BUTTON_MANUAL_ANN            40009
#define ID_BUTTON_INSTANT_ANN           40010
#define ID_BUTTON_GEN_GRID_POINTS       40011
#define ID_BUTTON_GEN_POINTS_MULTI_SEG  40022
#define ID_BUTTON_CHK_CONT_POINTS       40023
#define ID_BUTTON_PROFILE               40024
#define ID_BUTTON_PROFILE_EDIT          40025
#define ID_BUTTON_HALIGNMENT            40026
#define ID_BUTTON_EDIT_HALIGNMENT       40027
#define ID_BUTTON_ANN_HALIGNMENT        40029
#define ID_COMPACT_CONTOUR_LINES        40030
#define ID_SET_CONT_ANN_PARAMS          40031
#define ID_CROSSSECTION_DRAWCROSSSECTION 40032
#define ID_DRAW_X_SECTION               40033
#define ID_UTILITIES_ANNOTATECONTOURPOINTS 40034
#define ID_ANN_CONTOUR_PTS              40035
#define ID_DRAW_COORD_MARKER            40037
#define ID_EDIT_COORD_MARKER            40038
#define ID_INS_COORD_MARKER             40039
#define ID_PURGE_ALL                    40040
#define ID_DRAW_NEANN_ENTITY            40041
#define ID_EDIT_NEANN_ENTITY            40042
#define ID_BUTTON_INPUT                 40044
#define ID_CONTOUR                      40045
#define ID_BUTTON_ANNOTATION            40046
#define ID_BUTTON_PROFILE_MAIN          40047
#define ID_X_SECTION                    40048
#define ID_BUTTON_UTIL                  40049
#define ID_CALCULATE_VOLUME             40050
#define ID_BUTTON_REVERT_HALIGNMENT     40051
#define ID_DRAWCONTOUR_USER_SPEC        40052
#define ID_DEL_CONTOUR                  40053
#define IDS_CLIENT_NAME                 40054
#define ID_BUTTON_CONVERT_TOCONTOUR_ENT 40054
#define IDS_CLIENT_ADDRESS              40055
#define ID_DIVIDE_POLYLINE              40055
#define IDS_CLIENT_NAME_DEF             40056
#define ID_BUTTON_VALIGNMENT            40056
#define IDS_CLIENT_ADDRESS_DEF          40057
#define ID_BUTTON_EDIT_VALIGNMENT       40057
#define IDS_DEV_NAME                    40058
#define IDS_DEV_ADDRESS                 40059
#define IDS_DEV_NAME_DEF                40060
#define IDS_DEV_ADDRESS_DEF             40061
#define ID_REVERT_POLYLINE              40062

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        131
#define _APS_NEXT_COMMAND_VALUE         40058
#define _APS_NEXT_CONTROL_VALUE         1091
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
